package features.java15;

// https://openjdk.java.net/jeps/359
// https://openjdk.java.net/jeps/384
public class Records {

    // Enhance the Java programming language with records, which are classes that act as transparent carriers for immutable data.
    // Records can be thought of as nominal tuples.
    // The equals, hashCode, and toString methods, as well as the private, final fields, and public constructor, are generated by the Java compiler.
    record Point(int x, int y) {
    }

    public static void main(String[] args) {
        Point p = new Point(5, 6);
        int x = p.x();
        int y = p.y();
        String s = p.toString();
        boolean equals = p.equals(new Point(6, 7));
    }

}
